### ISSUE TITLE
How to recreate a view?

### ISSUE THREAD

**Issue by dmytrokyrychuk** [manuelnaranjo/django-database-view#11]
What is the intended way to recreate a view after changing the SQL?

Currently I am simply keeping the views in a separate app and running `./manage.py migrate APP zero && ./manage.py migrate APP` after modifying the views.

**Comment by moorchegue** [comment]
If I remember right `CreateView` drops existing views first, and then creates them again with the new SQL. So it should be enough to just run `migrate` once. Does that not work for you?

**Comment by dmytrokyrychuk** [comment]
Are you saying I can just duplicate the original `CreateView` migration?

**Comment by moorchegue** [comment]
Yeah, perhaps they won't be exactly the same if there're structural changes, otherwise should work.
