### ISSUE TITLE
is there plan to upload the latest version?

### ISSUE THREAD

**Issue by AndersonReyes** [manuelnaranjo/django-database-view#4]
Is there a plan to upload the latest version (master) to pypi?

**Comment by moorchegue** [comment]
Hey @manuelnaranjo, I'd be willing to take care of maintenance of this package if you don't have time. I'm currently working on a project that will use this extensively and could benefit from upgrading it regularly.

**Comment by manuelnaranjo** [comment]
hey @moorchegue sure I can transfer the ownership, I'm doing something totally different nowadays

**Comment by moorchegue** [comment]
Cool! My PyPI account is `murchik`.

**Comment by manuelnaranjo** [comment]
Ok that was easier than expected, I added you as contributor both to github and pypi, happy hacking :)

**Comment by moorchegue** [comment]
Awesome, thanks!

**Comment by moorchegue** [comment]
Latest version released.
